### ISSUE TITLE
Failed to load signer "signer #1"

### ISSUE THREAD

**Issue by SmartManoj** [shroudedcode/apk-mitm#115]
java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:663)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
        at at.favre.tools.apksigner.SignTool.sign(SignTool.java:314)
        at at.favre.tools.apksigner.SignTool.execute(SignTool.java:150)
        at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:45)
        at at.favre.tools.apksigner.SignTool.main(SignTool.java:33)
        
        
[signing.failed.log](https://github.com/shroudedcode/apk-mitm/files/9744273/signing.failed.log)

**Comment by SmartManoj** [comment]
https://github.com/r0adkll/sign-android-release/issues/1

**Comment by hungntv** [comment]
```
Failed to load signer "signer #1"
java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(Unknown Source)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(Unknown Source)
        at sun.security.provider.KeyStoreDelegator.engineLoad(Unknown Source)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(Unknown Source)
        at java.security.KeyStore.load(Unknown Source)
        at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
        at at.favre.tools.apksigner.SignTool.sign(SignTool.java:314)
        at at.favre.tools.apksigner.SignTool.execute(SignTool.java:150)
        at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:45)
        at at.favre.tools.apksigner.SignTool.main(SignTool.java:33)
```

**Comment by hungntv** [comment]
I got the same issue.

Did you find a solution? @SmartManoj 

```
Failed to load signer "signer #1"
java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(Unknown Source)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(Unknown Source)
        at sun.security.provider.KeyStoreDelegator.engineLoad(Unknown Source)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(Unknown Source)
        at java.security.KeyStore.load(Unknown Source)
        at com.android.apksigner.SignerParams.loadKeyStoreFromFile(SignerParams.java:353)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCertsFromKeyStore(SignerParams.java:239)
        at com.android.apksigner.SignerParams.loadPrivateKeyAndCerts(SignerParams.java:181)
        at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:277)
        at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:83)
        at at.favre.tools.apksigner.SignTool.sign(SignTool.java:314)
        at at.favre.tools.apksigner.SignTool.execute(SignTool.java:150)
        at at.favre.tools.apksigner.SignTool.mainExecute(SignTool.java:45)
        at at.favre.tools.apksigner.SignTool.main(SignTool.java:33)
```
