### ISSUE TITLE
Errors patching tiktok

### ISSUE THREAD

**Issue by monkeysuffrage** [shroudedcode/apk-mitm#13]
I get the following errors when I try to patch the latest tiktok:

```
npx apk-mitm tiktok-10-0-4.apk
npx: installed 139 in 7.834s

  ╭ apk-mitm v0.6.2
  ├ apktool v2.4.1
  ╰ uber-apk-signer v1.1.0

  Using temporary directory:
  C:\cygwin\tmp\99c476153a366865c82410ec6e6432aa

[12:41:37] Decoding APK file [started]
[12:41:37] → Using Apktool 2.4.1 on tiktok-10-0-4.apk
[12:41:37] → Loading resource table...
[12:41:39] Decoding APK file [failed]
[12:41:39] → Command failed with exit code 1: java -jar C:\Users\User\AppData\Roaming\npm-cache\_npx\30608\node_modules\apk-mitm\jar\apktool.jar decode C:\cygwin\home\User\node\tiktok\apk\tiktok-10-0-4.apk --output C:\cygwin\tmp\99c476153a366865c82410ec6e6432aa\decode

   Failed!  An error occurred:

 Error: Command failed with exit code 1: java -jar C:\Users\User\AppData\Roaming\npm-cache\_npx\30608\node_modules\apk-mitm\jar\apktool.jar decode C:\cygwin\home\User\node\tiktok\apk\tiktok-10-0-4.apk --output C:\cygwin\tmp\99c476153a366865c82410ec6e6432aa\decode

 Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
        at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:66)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
```

**Comment by shroudedcode** [comment]
This is a known issue with Apktool, so unfortunately there's nothing I can do about this at the moment. Please take a look at the following issues on their repository and upvote the ones relevant to your problem:

- https://github.com/iBotPeaches/Apktool/issues/2283
- https://github.com/iBotPeaches/Apktool/issues/2285
- https://github.com/iBotPeaches/Apktool/issues/2249
- https://github.com/iBotPeaches/Apktool/issues/1990
- https://github.com/iBotPeaches/Apktool/issues/2099

**Comment by monkeysuffrage** [comment]
Ok. I saw one that was closed on apktool because of a apk-mitm patch which is why I posted it here. I didn't really expect this to be resolved but was hoping for it anyway. Thanks for the good work.
