### ISSUE TITLE
error

### ISSUE THREAD

**Issue by anubi5egypt** [shroudedcode/apk-mitm#137]
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /usr/local/lib/node_modules/apk-mitm/dist/cli.js
- /usr/local/lib/node_modules/apk-mitm/bin/apk-mitm
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/apk-mitm/dist/cli.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/apk-mitm/dist/cli.js',
    '/usr/local/lib/node_modules/apk-mitm/bin/apk-mitm'
  ]
}

![2023-08-19_21-23](https://github.com/shroudedcode/apk-mitm/assets/42506882/391a00c7-d30f-45c3-aa82-d1040ff1da1f)

**Comment by anubi5egypt** [comment]
fixed
