### ISSUE TITLE
Code E404

### ISSUE THREAD

**Issue by FahmiRR** [shroudedcode/apk-mitm#20]
Hi,

This maybe will be a newbie mistake as this is my first time using node.js and tried to follow some instruction that required me to modify my apk 

I already had Node.js version 12+ and Java 8+ installed and I have been trying to modify my 'gojek.apk'

```
D:\my\directory\to\apk>npx apk-mitm gojek.apk
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tybys%2fcross-zip - Not found
npm ERR! 404
npm ERR! 404  '@tybys/cross-zip@^3.0.4' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'apk-mitm'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fahmi.rizaldi\AppData\Roaming\npm-cache\_logs\2020-08-06T08_58_33_260Z-debug.log
Install for [ 'apk-mitm@latest' ] failed with code 1
```

Is there anything I did incorrectly? 

Thanks

**Comment by shroudedcode** [comment]
> Is there anything I did incorrectly?

Nope, this is not your fault at all. npm (the package registry used by Node.js) is currently having some issues with the installation of scoped packages (like `@scope/package`) and `apk-mitm` happens to depend on at least one such package (`@tybys/cross-zip`, that's the one in your logs). The npm team is aware of this issue and you can follow it on [their status page](https://status.npmjs.org/incidents/cksjqc1w11v5). Once that is fixed, you should be able to `apk-mitm` normally.

**Comment by FahmiRR** [comment]
Ah so thats why, thanks for your response

**Comment by shroudedcode** [comment]
I just noticed that the URL in your logs (https://registry.npmjs.com/@tybys/cross-zip) is no longer returning a 404 error. Maybe you could try running `npx apk-mitm` again now.

**Comment by FahmiRR** [comment]
It is successfully downloaded but facing this error right now

```
npx: installed 123 in 25.043s

  ╭ apk-mitm v0.8.0
  ├ apktool v2.4.1
  ╰ uber-apk-signer v1.1.0

  Using temporary directory:
  C:\Users\FAHMI~1.RIZ\AppData\Local\Temp\831d017b5c621c8337f5b653ea760fc1

  √ Downloading tools
  × Decoding APK file
    → I: Copying unknown files...
    Modifying app manifest
    Modifying network security config
    Disabling certificate pinning
    Encoding patched APK file
    Signing patched APK file

   Failed!  An error occurred:

I: Using Apktool 2.4.1 on gojek.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\FAHMI~1.RIZ\AppData\Local\Temp\831d017b5c621c8337f5b653ea760fc1\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes9.dex...
I: Baksmaling classes10.dex...
I: Baksmaling classes11.dex...
I: Baksmaling classes12.dex...
I: Baksmaling classes13.dex...
I: Baksmaling classes14.dex...
I: Baksmaling classes15.dex...
I: Baksmaling classes16.dex...
I: Baksmaling classes17.dex...
I: Baksmaling classes18.dex...
I: Baksmaling classes19.dex...
I: Baksmaling classes20.dex...
I: Baksmaling classes21.dex...
I: Baksmaling classes22.dex...
I: Baksmaling classes23.dex...
I: Baksmaling classes24.dex...
I: Baksmaling classes25.dex...
I: Baksmaling classes26.dex...
I: Baksmaling classes27.dex...
I: Baksmaling classes28.dex...
I: Baksmaling classes29.dex...
I: Baksmaling classes30.dex...
I: Baksmaling classes31.dex...
I: Baksmaling classes32.dex...
I: Baksmaling classes33.dex...
I: Baksmaling classes34.dex...
I: Baksmaling classes35.dex...
I: Baksmaling classes36.dex...
I: Baksmaling classes37.dex...
I: Baksmaling classes38.dex...
I: Baksmaling classes39.dex...
I: Baksmaling classes40.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: aux.xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:214)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:180)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: Error copying file: aux.xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:207)
        ... 3 more
Caused by: java.io.FileNotFoundException: C:\Users\FAHMI~1.RIZ\AppData\Local\Temp\831d017b5c621c8337f5b653ea760fc1\decode\unknown\aux (The system cannot find the file specified)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
        ... 5 more
```

**Comment by shroudedcode** [comment]
@FahmiRR That's an entirely separate problem, let's continue in [this new issue](https://github.com/shroudedcode/apk-mitm/issues/21).
