### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by icoolguy1995** [shroudedcode/apk-mitm#52]
Hi, 

When I am trying to run mitm, I am getting the following error. Any leads?
```
PS C:\WINDOWS\system32> apk-mitm C:\Users\Spartan\Desktop\ig\123.apk

  ╭ apk-mitm v1.0.0
  ├ apktool v2.5.0
  ╰ uber-apk-signer v1.2.1

  Using temporary directory:
  C:\Users\Spartan\AppData\Local\Temp\apk-mitm-2be1f9e9eb89c90c804fb17571202453

  > Checking prerequisities
    √ Checking Node.js version
    × Checking Java version
      → Cannot read property '1' of null
      Downloading tools
    Decoding APK file
    Applying patches
    Encoding patched APK file
    Signing patched APK file

   Failed!  An error occurred:

TypeError: Cannot read property '1' of null
    at Object.getJavaVersion [as default] (C:\Users\Spartan\AppData\Roaming\npm\node_modules\apk-mitm\dist\utils\get-java-version.js:8:57)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Task.task (C:\Users\Spartan\AppData\Roaming\npm\node_modules\apk-mitm\dist\tasks\check-prerequisites.js:21:38)

  The full logs of all commands are available here:
  C:\Users\Spartan\AppData\Local\Temp\apk-mitm-2be1f9e9eb89c90c804fb17571202453\logs

PS C:\WINDOWS\system32> java -version
java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```

Also the logs folder it is indicating to check does not exist. Only the folder apk-mitm-2be1f9e9eb89c90c804fb17571202453 is there but it is empty.

**Comment by shroudedcode** [comment]
Whoops, this is a bug in [the code responsible for checking the Java version](https://github.com/shroudedcode/apk-mitm/blob/bf33e5e2c107e3dca56c7b87c8968212a4817e25/src/utils/get-java-version.ts) which is currently working under the assumption that the output of `java -version` always contains a major, a minor, and a patch version (like in `"15.0.2"`). In your case, however, it _only_ contains a major version (`"15"`). I'll release a fix for this in a second, thanks for reporting!
