### ISSUE TITLE
how to use apktool --only-main-classes in apk-mitm?

### ISSUE THREAD

**Issue by wuxiaohui94** [shroudedcode/apk-mitm#67]
```
Exception in thread "main" org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Not a valid dex magic value: cf 77 4c c7 9b 21 01 cd
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:93)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getVersion(DexBackedDexFile.java:157)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:81)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:184)
	at org.jf.dexlib2.dexbacked.ZipDexContainer$1.getDexFile(ZipDexContainer.java:181)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:89)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:98)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:151)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)
```
https://github.com/iBotPeaches/Apktool/issues/2239, I can use apktool d --only-main-classes to salve the problem,but I do not how to use --only-main-classes in the apk-mitm?

**Comment by shroudedcode** [comment]
Currently, there's no way to pass that flag to Apktool when running `apk-mitm`, but you could edit the (compiled) source code of the package if you want to try it. The relevant code is inside `dist/tools/apktool.js`. You have to add `'--only-main-classes'` before `'--output'` in both arrays.

I'm not sure this will fix your issue as I don't know how this affects the encoding process (i.e. whether the app is put together correctly again), but it's definitely worth a try.

**Comment by shroudedcode** [comment]
Closing this due to lack of a response.
